# Generated by Django 4.2.3 on 2026-06-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("RAZORPAY", "UPI/Net Banking (Razorpay)")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("UNPAID", "Unpaid"), ("PAID", "Paid"), ("FAILED", "Failed")],
                default="UNPAID",
                max_length=20,
            ),
        ),
    ]
